baseURL = "https://kahanat800.github.io/programmercarl-learn-record/"
languageCode = "zh-cn"
title = "木人的CS学习笔记"
theme = "PaperMod"
buildFuture = true
[taxonomies]
  tag = "tags"

[params]
  author = "KahanaT800"
  description = "算法刷题打卡 & CS 学习笔记"
  ShowToc = true
  TocOpen = true
  TocSide = "right"
  ShowCodeCopyButtons = true
  ShowReadingTime = false
  ShowBreadCrumbs = true
  defaultTheme = "auto"


[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    guessSyntax = true
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "打卡记录"
    url = "/days/"
    weight = 1
  [[menu.main]]
    name = "算法笔记"
    url = "/notes/algo/"
    weight = 2
  [[menu.main]]
    name = "OS 八股深入"
    url = "/notes/os/"
    weight = 3
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
